service: serverless-nodejs

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
#package:
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  hello:
    memory: 128
    handler: first.hello
    events:
      - http: POST hello
  echo:
    memory: 128
    handler: first.echo
    events:
      - http: POST echo

  sandbox:
    memory: 128
    handler: first.sandbox
    events:
     - http: GET sandbox

  insert:
    memory: 128
    handler: dynamo.insert
    events:
      - http: POST dynamo/insert
  select:
    memory: 128
    handler: dynamo.select
    events:
      - http: GET dynamo/select
  delete:
    memory: 128
    handler: dynamo.del
    events:
      - http: POST dynamo/delete

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage,self:provider.stage}-comments
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
                - dynamodb:UpdateItem
                - dynamodb:Scan
                - dynamodb:DescribeTable
              Resource: arn:aws:dynamodb:*:*:*
        Roles:
          - Ref: IamRoleLambdaExecution
